site_name: 'img-compressor'
site_description: 'Image compressor is a tool to compress images for web use build using python.'
repo_url: https://github.com/shuu05/img-compressor
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'
